# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: SrilalS.MeiliOps
PackageVersion: 0.4.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: MeiliOps
AppsAndFeaturesEntries:
- DisplayName: MeiliOps
  Publisher: MeiliOps contributors
  ProductCode: MeiliOps
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\MeiliOps'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SrilalS/MeiliOps/releases/download/v0.4.0/MeiliOps_0.4.0_x64-setup.exe
  InstallerSha256: 3F14C7D48389F13383A75EE6440D42F22E37EC966D8209520F8A015538B75EE3
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-09-29
